### ISSUE TITLE
<USA> - <Outdated starting production>

### ISSUE THREAD

**Issue by Kennelly1** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#48]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Yes i was

### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-2)

1.0.0-hotfix-2

### Description

```bash
USA has outdated Small Arms in its starting production line. Similarly, the produced ships are too old. For example the USS New Orleans should be, well, New Orleans Class (1933 cruiser) and not a late 19th century ship.

And the 1900 destroyer class was called Truxtun-class, not Truxton-class.
```

### Screenshots/Video

![Screenshot (1646)](https://user-images.githubusercontent.com/33550299/209830668-22f43731-441d-4853-8e4c-ee838720a3d6.png)
![Screenshot (1647)](https://user-images.githubusercontent.com/33550299/209830698-d0571be6-7e24-494e-9b5b-1e59559f9037.png)

**Comment by NotthatDonny** [comment]
This isn't a bug.  The US primary rifle was the M1903 Springfield until it was replaced by the M1 Garand.  The M1917 was only in very limited use (passed off to the Chemical Mortar Corps, actually) and was not in production after the war.

Navies will all be fixed in the next update.  But I have fixed these two errors with the US.
